/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecommerce.complaints.controller.api;

import com.ecommerce.complaints.model.generate.ErrorVTO;
import com.ecommerce.complaints.model.generate.GetPendingCount200Response;
import com.ecommerce.complaints.model.generate.ResponseApprovalDTO;
import com.ecommerce.complaints.model.generate.ResponseReviewVTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Response Approval", description = "the Response Approval API")
public interface ResponseApprovalApi {

    /**
     * GET /complaints/responses/pending : Get pending responses for approval
     *
     * @return List of pending responses (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getPendingApprovals",
        summary = "Get pending responses for approval",
        tags = { "Response Approval" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of pending responses", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ResponseReviewVTO.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/complaints/responses/pending",
        produces = { "application/json" }
    )
    ResponseEntity<List<ResponseReviewVTO>> getPendingApprovals(
        
    );


    /**
     * GET /complaints/responses/pending/count : Get count of pending responses
     *
     * @return Count of pending responses (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getPendingCount",
        summary = "Get count of pending responses",
        tags = { "Response Approval" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Count of pending responses", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetPendingCount200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/complaints/responses/pending/count",
        produces = { "application/json" }
    )
    ResponseEntity<GetPendingCount200Response> getPendingCount(
        
    );


    /**
     * POST /complaints/responses/review : Review and approve/reject/edit response
     *
     * @param responseApprovalDTO  (required)
     * @return Response reviewed successfully (status code 200)
     *         or Bad request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "reviewResponse",
        summary = "Review and approve/reject/edit response",
        tags = { "Response Approval" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Response reviewed successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseReviewVTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorVTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/complaints/responses/review",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ResponseReviewVTO> reviewResponse(
        @Parameter(name = "ResponseApprovalDTO", description = "", required = true) @Valid @RequestBody ResponseApprovalDTO responseApprovalDTO
    );

}
